seed: 42
torch_deterministic: true
cuda: true
track: true
wandb_project_name: "MultiAgent-Experiments-MAPPO"
capture_video: true
wandb_entity: 'mingwhy-university-of-washington'

# Learning params
lr: 2.5e-4
n_episodes: 15000
update_every: 4
num_envs: 1
num_steps: 128
num_minibatches: 4
total_timesteps: 12800000
anneal_lr: true
gae_lambda: 0.95
update_epochs: 4
norm_adv: true
initial_memory: 2000
clip_vloss: true
clip_coef: 0.2
gamma: 0.99
ent_coef: 0.01
max_grad_norm: 0.5
vf_coef: 0.5
target_kl: None

# Logistics params
save_model_episode: 10000
visualize_every: 5000  # how many episodes before making a video
log_episode: 500
log_step: 100
version: "short"
print_every: 10
base_save_path: ''
load_model_start_path: 'models/'
track_wandb: true
track: true

# Loss weights
dqn_loss_weight: 1

# architecture
fc_direction: 8
cumulants: 64
filters: 32
kernel_size: 3
fc: 256

mode: ppo
mappo: false
load_model_start_path: models
env_id: "MultiGrid-Cluttered-Fixed-15x15"
exp_name : "MultiGrid-Cluttered-Fixed-15x15"
device: cpu